name: 'Upload'
description: 'Upload documents to the HQ Pages'
inputs:
  bucket:
    description: 'GCS bucket name'
    required: false
    default: 'hq-pages'
  source:
    description: 'Path to documents directory'
    required: false
    default: docs
  namespace:
    description: 'Document namespace in HQ Pages'
    required: true
runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.8.1
      with:
        workload_identity_provider: projects/705797626452/locations/global/workloadIdentityPools/github-actions/providers/github-actions
        service_account: github-actions@hq-pages.iam.gserviceaccount.com
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
    - name: Sync documents
      shell: bash
      run: gsutil -m rsync -d -r ${{inputs.source}} gs://${{inputs.bucket}}/${{inputs.namespace}}
