name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.8.1
        with:
          workload_identity_provider: projects/705797626452/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@hq-pages.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Deploy mouseion to GAE
        run: gcloud app deploy --project hq-pages
